apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: frontend
    team: developer
    k8fundamentals: test label addition
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80